QT       += core gui
#QT += 3dcore 3drender 3dinput 3dextras

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

CONFIG += c++11

# You can make your code fail to compile if it uses deprecated APIs.
# In order to do so, uncomment the following line.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

SOURCES += \
    BaseClass/DigitalTransport/UARTDataChannel.cpp \
    BaseClass/DigitalTransport/UDPDataChannel.cpp \
    BaseClass/OSD/Bitmap.cpp \
    BaseClass/OSD/Marker.cpp \
    attitudeview.cpp \
    headingmeter.cpp \
    levelmeter.cpp \
    main.cpp \
    mainwindow.cpp \
    indexform.cpp \
    mainform.cpp \
    playwindow.cpp \
    XiheClient.cpp \
    App.cpp \
    BaseClass/CommonTools/ExBuff.cpp \
    BaseClass/CommonTools/FlexibleBuff.cpp \
    BaseClass/CommonTools/RtspParser.cpp \
    BaseClass/CommonTools/SdpParser.cpp \
    BaseClass/CommonTools/SignalObject.cpp \
    BaseClass/CommonTools/TimeCounter.cpp \
    BaseClass/DigitalTransport/DigitalTransport.cpp \
    BaseClass/FEC/FEC2DTable.cpp \
    BaseClass/FEC/FECDecoder.cpp \
    BaseClass/FEC/FECEncoder.cpp \
    BaseClass/ImageTransoprt/ImageTransoprt.cpp \
    BaseClass/Log/Log.cpp \
    BaseClass/MediaCapture/VideoCapture.cpp \
    BaseClass/MediaDecoder/VideoDecoder.cpp \
    BaseClass/MediaEncoder/VideoEncoder.cpp \
    BaseClass/MP4Tool/MP4Reader.cpp \
    BaseClass/MP4Tool/MP4Writer.cpp \
    BaseClass/OSD/OSD.cpp \
    BaseClass/RTPPacketizer/H264RTPpacketizer.cpp \
    BaseClass/RTPParser/H264RTPParser.cpp \
    BaseClass/RTSPClient/RTSPClient.cpp \
    BaseClass/RTSPServer/RTSPServer.cpp \
    BaseClass/RTSPServer/RTSPServerSession.cpp \
    rocker.cpp

HEADERS += \
    BaseClass/DigitalTransport/DataChannel.h \
    BaseClass/DigitalTransport/UARTDataChannel.h \
    BaseClass/DigitalTransport/UDPDataChannel.h \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/ardupilotmega.h \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/ardupilotmega.hpp \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/gtestsuite.hpp \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink.h \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_adap_tuning.h \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_adap_tuning.hpp \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_ahrs.h \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_ahrs.hpp \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_ahrs2.h \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_ahrs2.hpp \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_ahrs3.h \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_ahrs3.hpp \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_airspeed_autocal.h \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_airspeed_autocal.hpp \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_aoa_ssa.h \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_aoa_ssa.hpp \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_ap_adc.h \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_ap_adc.hpp \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_autopilot_version_request.h \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_autopilot_version_request.hpp \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_battery2.h \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_battery2.hpp \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_camera_feedback.h \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_camera_feedback.hpp \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_camera_status.h \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_camera_status.hpp \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_compassmot_status.h \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_compassmot_status.hpp \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_data16.h \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_data16.hpp \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_data32.h \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_data32.hpp \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_data64.h \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_data64.hpp \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_data96.h \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_data96.hpp \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_deepstall.h \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_deepstall.hpp \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_device_op_read.h \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_device_op_read.hpp \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_device_op_read_reply.h \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_device_op_read_reply.hpp \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_device_op_write.h \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_device_op_write.hpp \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_device_op_write_reply.h \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_device_op_write_reply.hpp \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_digicam_configure.h \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_digicam_configure.hpp \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_digicam_control.h \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_digicam_control.hpp \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_ekf_status_report.h \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_ekf_status_report.hpp \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_esc_telemetry_1_to_4.h \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_esc_telemetry_1_to_4.hpp \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_esc_telemetry_5_to_8.h \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_esc_telemetry_5_to_8.hpp \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_esc_telemetry_9_to_12.h \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_esc_telemetry_9_to_12.hpp \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_fence_fetch_point.h \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_fence_fetch_point.hpp \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_fence_point.h \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_fence_point.hpp \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_gimbal_control.h \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_gimbal_control.hpp \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_gimbal_report.h \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_gimbal_report.hpp \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_gimbal_torque_cmd_report.h \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_gimbal_torque_cmd_report.hpp \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_gopro_get_request.h \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_gopro_get_request.hpp \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_gopro_get_response.h \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_gopro_get_response.hpp \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_gopro_heartbeat.h \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_gopro_heartbeat.hpp \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_gopro_set_request.h \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_gopro_set_request.hpp \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_gopro_set_response.h \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_gopro_set_response.hpp \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_hwstatus.h \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_hwstatus.hpp \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_led_control.h \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_led_control.hpp \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_limits_status.h \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_limits_status.hpp \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_mag_cal_progress.h \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_mag_cal_progress.hpp \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_mcu_status.h \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_mcu_status.hpp \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_meminfo.h \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_meminfo.hpp \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_mount_configure.h \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_mount_configure.hpp \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_mount_control.h \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_mount_control.hpp \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_mount_status.h \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_mount_status.hpp \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_obstacle_distance_3d.h \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_obstacle_distance_3d.hpp \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_osd_param_config.h \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_osd_param_config.hpp \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_osd_param_config_reply.h \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_osd_param_config_reply.hpp \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_osd_param_show_config.h \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_osd_param_show_config.hpp \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_osd_param_show_config_reply.h \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_osd_param_show_config_reply.hpp \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_pid_tuning.h \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_pid_tuning.hpp \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_radio.h \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_radio.hpp \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_rally_fetch_point.h \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_rally_fetch_point.hpp \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_rally_point.h \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_rally_point.hpp \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_rangefinder.h \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_rangefinder.hpp \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_remote_log_block_status.h \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_remote_log_block_status.hpp \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_remote_log_data_block.h \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_remote_log_data_block.hpp \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_rpm.h \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_rpm.hpp \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_sensor_offsets.h \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_sensor_offsets.hpp \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_set_mag_offsets.h \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_set_mag_offsets.hpp \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_simstate.h \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_simstate.hpp \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_vision_position_delta.h \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_vision_position_delta.hpp \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_water_depth.h \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_water_depth.hpp \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_wind.h \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/mavlink_msg_wind.hpp \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/testsuite.h \
    BaseClass/DigitalTransport/mavlink/ardupilotmega/version.h \
    BaseClass/DigitalTransport/mavlink/checksum.h \
    BaseClass/DigitalTransport/mavlink/common/common.h \
    BaseClass/DigitalTransport/mavlink/common/common.hpp \
    BaseClass/DigitalTransport/mavlink/common/gtestsuite.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_actuator_control_target.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_actuator_control_target.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_actuator_output_status.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_actuator_output_status.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_adsb_vehicle.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_adsb_vehicle.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_ais_vessel.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_ais_vessel.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_altitude.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_altitude.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_att_pos_mocap.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_att_pos_mocap.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_attitude.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_attitude.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_attitude_quaternion.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_attitude_quaternion.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_attitude_quaternion_cov.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_attitude_quaternion_cov.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_attitude_target.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_attitude_target.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_auth_key.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_auth_key.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_autopilot_state_for_gimbal_device.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_autopilot_state_for_gimbal_device.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_autopilot_version.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_autopilot_version.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_battery_status.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_battery_status.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_button_change.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_button_change.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_camera_capture_status.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_camera_capture_status.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_camera_fov_status.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_camera_fov_status.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_camera_image_captured.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_camera_image_captured.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_camera_information.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_camera_information.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_camera_settings.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_camera_settings.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_camera_tracking_geo_status.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_camera_tracking_geo_status.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_camera_tracking_image_status.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_camera_tracking_image_status.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_camera_trigger.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_camera_trigger.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_can_filter_modify.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_can_filter_modify.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_can_frame.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_can_frame.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_canfd_frame.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_canfd_frame.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_cellular_config.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_cellular_config.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_cellular_status.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_cellular_status.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_change_operator_control.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_change_operator_control.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_change_operator_control_ack.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_change_operator_control_ack.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_collision.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_collision.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_command_ack.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_command_ack.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_command_cancel.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_command_cancel.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_command_int.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_command_int.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_command_long.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_command_long.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_component_information.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_component_information.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_component_metadata.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_component_metadata.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_control_system_state.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_control_system_state.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_current_event_sequence.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_current_event_sequence.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_data_stream.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_data_stream.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_data_transmission_handshake.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_data_transmission_handshake.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_debug.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_debug.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_debug_float_array.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_debug_float_array.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_debug_vect.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_debug_vect.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_distance_sensor.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_distance_sensor.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_efi_status.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_efi_status.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_encapsulated_data.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_encapsulated_data.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_esc_info.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_esc_info.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_esc_status.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_esc_status.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_estimator_status.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_estimator_status.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_event.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_event.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_extended_sys_state.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_extended_sys_state.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_fence_status.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_fence_status.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_file_transfer_protocol.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_file_transfer_protocol.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_flight_information.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_flight_information.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_follow_target.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_follow_target.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_generator_status.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_generator_status.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_gimbal_device_attitude_status.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_gimbal_device_attitude_status.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_gimbal_device_information.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_gimbal_device_information.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_gimbal_device_set_attitude.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_gimbal_device_set_attitude.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_gimbal_manager_information.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_gimbal_manager_information.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_gimbal_manager_set_attitude.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_gimbal_manager_set_attitude.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_gimbal_manager_set_manual_control.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_gimbal_manager_set_manual_control.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_gimbal_manager_set_pitchyaw.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_gimbal_manager_set_pitchyaw.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_gimbal_manager_status.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_gimbal_manager_status.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_global_position_int.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_global_position_int.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_global_position_int_cov.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_global_position_int_cov.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_global_vision_position_estimate.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_global_vision_position_estimate.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_gps2_raw.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_gps2_raw.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_gps2_rtk.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_gps2_rtk.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_gps_global_origin.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_gps_global_origin.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_gps_inject_data.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_gps_inject_data.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_gps_input.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_gps_input.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_gps_raw_int.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_gps_raw_int.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_gps_rtcm_data.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_gps_rtcm_data.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_gps_rtk.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_gps_rtk.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_gps_status.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_gps_status.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_high_latency.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_high_latency.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_high_latency2.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_high_latency2.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_highres_imu.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_highres_imu.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_hil_actuator_controls.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_hil_actuator_controls.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_hil_controls.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_hil_controls.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_hil_gps.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_hil_gps.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_hil_optical_flow.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_hil_optical_flow.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_hil_rc_inputs_raw.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_hil_rc_inputs_raw.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_hil_sensor.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_hil_sensor.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_hil_state.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_hil_state.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_hil_state_quaternion.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_hil_state_quaternion.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_home_position.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_home_position.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_hygrometer_sensor.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_hygrometer_sensor.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_isbd_link_status.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_isbd_link_status.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_landing_target.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_landing_target.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_link_node_status.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_link_node_status.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_local_position_ned.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_local_position_ned.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_local_position_ned_cov.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_local_position_ned_cov.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_local_position_ned_system_global_offset.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_local_position_ned_system_global_offset.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_log_data.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_log_data.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_log_entry.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_log_entry.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_log_erase.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_log_erase.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_log_request_data.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_log_request_data.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_log_request_end.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_log_request_end.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_log_request_list.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_log_request_list.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_logging_ack.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_logging_ack.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_logging_data.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_logging_data.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_logging_data_acked.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_logging_data_acked.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_mag_cal_report.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_mag_cal_report.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_manual_control.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_manual_control.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_manual_setpoint.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_manual_setpoint.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_memory_vect.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_memory_vect.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_message_interval.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_message_interval.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_mission_ack.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_mission_ack.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_mission_clear_all.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_mission_clear_all.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_mission_count.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_mission_count.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_mission_current.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_mission_current.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_mission_item.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_mission_item.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_mission_item_int.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_mission_item_int.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_mission_item_reached.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_mission_item_reached.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_mission_request.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_mission_request.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_mission_request_int.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_mission_request_int.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_mission_request_list.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_mission_request_list.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_mission_request_partial_list.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_mission_request_partial_list.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_mission_set_current.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_mission_set_current.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_mission_write_partial_list.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_mission_write_partial_list.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_mount_orientation.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_mount_orientation.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_named_value_float.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_named_value_float.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_named_value_int.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_named_value_int.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_nav_controller_output.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_nav_controller_output.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_obstacle_distance.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_obstacle_distance.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_odometry.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_odometry.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_onboard_computer_status.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_onboard_computer_status.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_open_drone_id_arm_status.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_open_drone_id_arm_status.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_open_drone_id_authentication.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_open_drone_id_authentication.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_open_drone_id_basic_id.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_open_drone_id_basic_id.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_open_drone_id_location.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_open_drone_id_location.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_open_drone_id_message_pack.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_open_drone_id_message_pack.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_open_drone_id_operator_id.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_open_drone_id_operator_id.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_open_drone_id_self_id.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_open_drone_id_self_id.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_open_drone_id_system.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_open_drone_id_system.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_open_drone_id_system_update.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_open_drone_id_system_update.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_optical_flow.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_optical_flow.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_optical_flow_rad.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_optical_flow_rad.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_orbit_execution_status.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_orbit_execution_status.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_param_ext_ack.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_param_ext_ack.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_param_ext_request_list.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_param_ext_request_list.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_param_ext_request_read.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_param_ext_request_read.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_param_ext_set.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_param_ext_set.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_param_ext_value.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_param_ext_value.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_param_map_rc.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_param_map_rc.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_param_request_list.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_param_request_list.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_param_request_read.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_param_request_read.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_param_set.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_param_set.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_param_value.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_param_value.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_ping.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_ping.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_play_tune.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_play_tune.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_play_tune_v2.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_play_tune_v2.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_position_target_global_int.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_position_target_global_int.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_position_target_local_ned.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_position_target_local_ned.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_power_status.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_power_status.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_radio_status.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_radio_status.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_raw_imu.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_raw_imu.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_raw_pressure.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_raw_pressure.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_raw_rpm.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_raw_rpm.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_rc_channels.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_rc_channels.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_rc_channels_override.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_rc_channels_override.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_rc_channels_raw.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_rc_channels_raw.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_rc_channels_scaled.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_rc_channels_scaled.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_request_data_stream.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_request_data_stream.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_request_event.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_request_event.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_resource_request.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_resource_request.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_response_event_error.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_response_event_error.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_safety_allowed_area.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_safety_allowed_area.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_safety_set_allowed_area.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_safety_set_allowed_area.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_scaled_imu.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_scaled_imu.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_scaled_imu2.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_scaled_imu2.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_scaled_imu3.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_scaled_imu3.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_scaled_pressure.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_scaled_pressure.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_scaled_pressure2.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_scaled_pressure2.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_scaled_pressure3.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_scaled_pressure3.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_serial_control.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_serial_control.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_servo_output_raw.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_servo_output_raw.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_set_actuator_control_target.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_set_actuator_control_target.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_set_attitude_target.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_set_attitude_target.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_set_gps_global_origin.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_set_gps_global_origin.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_set_home_position.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_set_home_position.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_set_mode.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_set_mode.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_set_position_target_global_int.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_set_position_target_global_int.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_set_position_target_local_ned.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_set_position_target_local_ned.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_setup_signing.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_setup_signing.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_sim_state.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_sim_state.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_smart_battery_info.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_smart_battery_info.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_statustext.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_statustext.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_storage_information.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_storage_information.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_supported_tunes.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_supported_tunes.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_sys_status.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_sys_status.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_system_time.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_system_time.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_terrain_check.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_terrain_check.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_terrain_data.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_terrain_data.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_terrain_report.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_terrain_report.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_terrain_request.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_terrain_request.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_time_estimate_to_target.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_time_estimate_to_target.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_timesync.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_timesync.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_trajectory_representation_bezier.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_trajectory_representation_bezier.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_trajectory_representation_waypoints.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_trajectory_representation_waypoints.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_tunnel.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_tunnel.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_uavcan_node_info.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_uavcan_node_info.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_uavcan_node_status.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_uavcan_node_status.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_utm_global_position.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_utm_global_position.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_v2_extension.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_v2_extension.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_vfr_hud.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_vfr_hud.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_vibration.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_vibration.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_vicon_position_estimate.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_vicon_position_estimate.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_video_stream_information.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_video_stream_information.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_video_stream_status.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_video_stream_status.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_vision_position_estimate.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_vision_position_estimate.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_vision_speed_estimate.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_vision_speed_estimate.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_wheel_distance.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_wheel_distance.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_wifi_config_ap.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_wifi_config_ap.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_winch_status.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_winch_status.hpp \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_wind_cov.h \
    BaseClass/DigitalTransport/mavlink/common/mavlink_msg_wind_cov.hpp \
    BaseClass/DigitalTransport/mavlink/common/testsuite.h \
    BaseClass/DigitalTransport/mavlink/common/version.h \
    BaseClass/DigitalTransport/mavlink/icarous/gtestsuite.hpp \
    BaseClass/DigitalTransport/mavlink/icarous/icarous.h \
    BaseClass/DigitalTransport/mavlink/icarous/icarous.hpp \
    BaseClass/DigitalTransport/mavlink/icarous/mavlink.h \
    BaseClass/DigitalTransport/mavlink/icarous/mavlink_msg_icarous_heartbeat.h \
    BaseClass/DigitalTransport/mavlink/icarous/mavlink_msg_icarous_heartbeat.hpp \
    BaseClass/DigitalTransport/mavlink/icarous/mavlink_msg_icarous_kinematic_bands.h \
    BaseClass/DigitalTransport/mavlink/icarous/mavlink_msg_icarous_kinematic_bands.hpp \
    BaseClass/DigitalTransport/mavlink/icarous/testsuite.h \
    BaseClass/DigitalTransport/mavlink/icarous/version.h \
    BaseClass/DigitalTransport/mavlink/mavlink_conversions.h \
    BaseClass/DigitalTransport/mavlink/mavlink_get_info.h \
    BaseClass/DigitalTransport/mavlink/mavlink_helpers.h \
    BaseClass/DigitalTransport/mavlink/mavlink_sha256.h \
    BaseClass/DigitalTransport/mavlink/mavlink_types.h \
    BaseClass/DigitalTransport/mavlink/message.hpp \
    BaseClass/DigitalTransport/mavlink/minimal/gtestsuite.hpp \
    BaseClass/DigitalTransport/mavlink/minimal/mavlink.h \
    BaseClass/DigitalTransport/mavlink/minimal/mavlink_msg_heartbeat.h \
    BaseClass/DigitalTransport/mavlink/minimal/mavlink_msg_heartbeat.hpp \
    BaseClass/DigitalTransport/mavlink/minimal/mavlink_msg_protocol_version.h \
    BaseClass/DigitalTransport/mavlink/minimal/mavlink_msg_protocol_version.hpp \
    BaseClass/DigitalTransport/mavlink/minimal/minimal.h \
    BaseClass/DigitalTransport/mavlink/minimal/minimal.hpp \
    BaseClass/DigitalTransport/mavlink/minimal/testsuite.h \
    BaseClass/DigitalTransport/mavlink/minimal/version.h \
    BaseClass/DigitalTransport/mavlink/msgmap.hpp \
    BaseClass/DigitalTransport/mavlink/protocol.h \
    BaseClass/DigitalTransport/mavlink/uAvionix/gtestsuite.hpp \
    BaseClass/DigitalTransport/mavlink/uAvionix/mavlink.h \
    BaseClass/DigitalTransport/mavlink/uAvionix/mavlink_msg_uavionix_adsb_out_cfg.h \
    BaseClass/DigitalTransport/mavlink/uAvionix/mavlink_msg_uavionix_adsb_out_cfg.hpp \
    BaseClass/DigitalTransport/mavlink/uAvionix/mavlink_msg_uavionix_adsb_out_dynamic.h \
    BaseClass/DigitalTransport/mavlink/uAvionix/mavlink_msg_uavionix_adsb_out_dynamic.hpp \
    BaseClass/DigitalTransport/mavlink/uAvionix/mavlink_msg_uavionix_adsb_transceiver_health_report.h \
    BaseClass/DigitalTransport/mavlink/uAvionix/mavlink_msg_uavionix_adsb_transceiver_health_report.hpp \
    BaseClass/DigitalTransport/mavlink/uAvionix/testsuite.h \
    BaseClass/DigitalTransport/mavlink/uAvionix/uAvionix.h \
    BaseClass/DigitalTransport/mavlink/uAvionix/uAvionix.hpp \
    BaseClass/DigitalTransport/mavlink/uAvionix/version.h \
    BaseClass/OSD/Bitmap.h \
    BaseClass/OSD/Marker.h \
    attitudeview.h \
    headingmeter.h \
    levelmeter.h \
    mainwindow.h \
    indexform.h \
    mainform.h \
    playwindow.h \
    XiheClient.h \
    App.h \
    BaseClass/CommonTools/ExBuff.h \
    BaseClass/CommonTools/FlexibleBuff.h \
    BaseClass/CommonTools/RtspParser.h \
    BaseClass/CommonTools/SdpParser.h \
    BaseClass/CommonTools/SignalObject.h \
    BaseClass/CommonTools/TimeCounter.h \
    BaseClass/DigitalTransport/DigitalTransport.h \
    BaseClass/FEC/FEC2DTable.h \
    BaseClass/FEC/FECDecoder.h \
    BaseClass/FEC/FECEncoder.h \
    BaseClass/ImageTransoprt/ImageTransoprt.h \
    BaseClass/Log/Log.h \
    BaseClass/MediaCapture/VideoCapture.h \
    BaseClass/MediaDecoder/VideoDecoder.h \
    BaseClass/MediaEncoder/VideoEncoder.h \
    BaseClass/MP4Tool/MP4Reader.h \
    BaseClass/MP4Tool/MP4Writer.h \
    BaseClass/OSD/OSD.h \
    BaseClass/RTPPacketizer/H264RTPpacketizer.h \
    BaseClass/RTPPacketizer/RTPPacketizer.h \
    BaseClass/RTPParser/H264RTPParser.h \
    BaseClass/RTPParser/RTPParser.h \
    BaseClass/RTSPClient/RTSPClient.h \
    BaseClass/RTSPServer/RTSPServer.h \
    BaseClass/RTSPServer/RTSPServerSession.h \
    BaseClass/Common.h \
    rocker.h

INCLUDEPATH += \
    BaseClass  \
    BaseClass/CommonTools  \
    BaseClass/DigitalTransport \
    BaseClass/FEC \
    BaseClass/ImageTransoprt \
    BaseClass/Log \
    BaseClass/MediaCapture \
    BaseClass/MediaDecoder \
    BaseClass/MediaEncoder \
    BaseClass/MP4Tool \
    BaseClass/OSD \
    BaseClass/RTPPacketizer \
    BaseClass/RTPParser \
    BaseClass/RTSPClient \
    BaseClass/RTSPServer

FORMS += \
    attitudeview.ui \
    headingmeter.ui \
    levelmeter.ui \
    mainwindow.ui \
    indexform.ui \
    mainform.ui \
    rocker.ui

LIBS += -L /usr/local/lib  -l"pthread" -l"avcodec" -l"avformat" -l"avutil" -l"swscale" -l"bcm_host" -l"SDL2" -l"wiringPi" -l"freetype" -l"dl"

TRANSLATIONS += \
    XiHeClient_zh_CN.ts

# Default rules for deployment.
qnx: target.path = /tmp/$${TARGET}/bin
else: unix:!android: target.path = /opt/$${TARGET}/bin
!isEmpty(target.path): INSTALLS += target

RESOURCES += \
    background.qrc
